export const types={
    LOGIN_LOADER:'LOGIN_LOADER',
    INCREASE_COUNTER_ASYNC:'INCREASE_COUNTER_ASYNC',
    INCREASE_COUNTER:'INCREASE_COUNTER',
    API_LIST:'API_LIST',
    API_LIST_SUCCESS:'API_LIST_SUCCESS',
    GET_API:'GET_API',
    
} ;